# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Svelte Check
on:
  push:
    branches: ['main', 'feat/svelte-app']
  pull_request:
    branches: ['main', 'feat/svelte-app']

jobs:
  prettier:
    name: Svelte Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check svelte/ts with svelte-check
        run: npm run check
